[package]
name = "obs-toys"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
dotenvy = "0.15.7"
obws = "0.13.0"
thiserror = "2.0.2"
tokio = { version = "1.41.1", features = ["full"] }
uuid = { version = "1.11.0", features = ["v4", "serde"] }
